volumes:
 mongodb_data: { driver: local }

services:
 rocketchat:
   image: registry.rocket.chat/rocketchat/rocket.chat:4.8.1
   restart: on-failure
   volumes:
      - ./data/uploads:/app/uploads
   labels:
     traefik.enable: "true"
     traefik.http.routers.rocketchat.rule: Host(`${DOMAIN}`)
     traefik.http.routers.rocketchat.tls: "true"
     traefik.http.routers.rocketchat.entrypoints: https
     traefik.http.routers.rocketchat.tls.certresolver: le
   environment:
     MONGO_URL: "mongodb://mongodb:27017/rocketchat?replicaSet=rs0"
     MONGO_OPLOG_URL: "mongodb://mongodb:27017/local?replicaSet=rs0"
     ROOT_URL: "http://localhost:3006"
     PORT: "3006"
     DEPLOY_METHOD: docker
     DEPLOY_PLATFORM: ${DEPLOY_PLATFORM}
   depends_on:
     - mongodb
   expose:
     - "3006"
   ports:
     - "0.0.0.0:3006:3006"


 mongodb:
    image: docker.io/bitnami/mongodb:4.4
    restart: unless-stopped
    volumes:
      - ./data/db:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ENABLE_JOURNAL: ${MONGODB_ENABLE_JOURNAL:-true}
      ALLOW_EMPTY_PASSWORD: ${ALLOW_EMPTY_PASSWORD:-yes}